name: Update Blog Posts

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Test curl
        run: |
          curl -v https://misslogs.klka.in/index.xml
    
      - uses: actions/checkout@v4
      
      - name: Clone blog repository
        run: |
          git clone https://x-access-token:${{ secrets.BLOG_TOKEN }}@github.com/kamalkoranga/blogs.git blog

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Hugo
        run: |
          cd blog
          hugo

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Update README
        run: python scripts/update_blog.py

      - name: Commit changes
        run: |
          git config user.name "KLKA"
          git config user.email "83089446+kamalkoranga@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update latest blog posts"
          git push
